language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
sudo: required
install:
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      # Install OpenAL, VorbisFile, OpusFile, FLAC, libsndfile, libmpg123,
      # PhysicsFS, and DUMB dependencies for decoders and examples.
      sudo apt-get install -qq \
        libopenal-dev \
        libvorbis-dev \
        libopus-dev \
        libflac-dev \
        libsndfile1-dev \
        libmpg123-dev \
        libphysfs-dev \
        libdumb1-dev
    fi
script:
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      cmake .
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      cmake .
    fi
  - make -j2
